-- Detailed shelter partner application (verification dossier)

ALTER TABLE shelters
    ADD COLUMN legal_entity_name VARCHAR(255) NULL,
    ADD COLUMN ein_or_tax_id VARCHAR(64) NULL,
    ADD COLUMN year_founded INT NULL,
    ADD COLUMN website_url VARCHAR(512) NULL,
    ADD COLUMN facility_address TEXT NULL,
    ADD COLUMN mailing_same_as_facility TINYINT(1) NULL,
    ADD COLUMN mailing_address TEXT NULL,
    ADD COLUMN animal_focus VARCHAR(128) NULL,
    ADD COLUMN avg_monthly_intakes INT NULL,
    ADD COLUMN avg_cats_in_care INT NULL,
    ADD COLUMN staffing_overview TEXT NULL,
    ADD COLUMN volunteer_program_summary TEXT NULL,
    ADD COLUMN state_license_status VARCHAR(32) NULL,
    ADD COLUMN home_visit_policy VARCHAR(32) NULL,
    ADD COLUMN adoption_fee_policy TEXT NULL,
    ADD COLUMN spay_neuter_policy TEXT NULL,
    ADD COLUMN return_policy TEXT NULL,
    ADD COLUMN medical_care_description TEXT NULL,
    ADD COLUMN behavior_modification_resources TEXT NULL,
    ADD COLUMN transport_assistance_notes TEXT NULL,
    ADD COLUMN disaster_contingency_plan TEXT NULL,
    ADD COLUMN character_references TEXT NULL,
    ADD COLUMN mission_statement TEXT NULL,
    ADD COLUMN board_chair_or_director_contact TEXT NULL,
    ADD COLUMN social_website_handles TEXT NULL,
    ADD COLUMN doc_nonprofit_url VARCHAR(1024) NULL,
    ADD COLUMN doc_facility_license_url VARCHAR(1024) NULL,
    ADD COLUMN doc_insurance_url VARCHAR(1024) NULL,
    ADD COLUMN doc_protocols_url VARCHAR(1024) NULL,
    ADD COLUMN profile_completed_at TIMESTAMP(6) NULL,
    ADD COLUMN profile_last_saved_at TIMESTAMP(6) NULL;
