CREATE TABLE pawvet_triage_cases (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    cat_id BIGINT NULL,
    cat_name VARCHAR(255) NOT NULL,
    cat_snapshot_json TEXT NULL,
    symptoms TEXT NOT NULL,
    media_description TEXT NOT NULL,
    attachment_urls_json TEXT NULL,
    urgency VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    vet_user_id BIGINT NULL,
    vet_display_name VARCHAR(255) NULL,
    vet_avatar_url VARCHAR(1024) NULL,
    messages_json LONGTEXT NOT NULL,
    summary TEXT NULL,
    resolved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ptc_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_ptc_vet FOREIGN KEY (vet_user_id) REFERENCES users (id),
    INDEX idx_ptc_status_created (status, created_at),
    INDEX idx_ptc_owner_created (owner_user_id, created_at),
    INDEX idx_ptc_vet_status (vet_user_id, status)
);
